# This is the definitive Netlify configuration file.

# [build] section: Tells Netlify how to build your frontend.
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# [functions] section: Solves the "axios" not found error.
[functions]
  node_bundler = "esbuild"

# [[redirects]] for the API: This MUST come first.
# It proxies requests from "/api/..." to your function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# [[redirects]] for the React App: This MUST come last.
# This is the "catch-all" rule for your single-page app.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200