# This is the final, correct netlify.toml file.

[build]
  # Command to build your Vite frontend
  command = "npm run build"
  # The directory where the built frontend files are located
  publish = "dist"
  # The directory where your serverless functions are located
  functions = "netlify/functions"

# This new section solves the dependency issue.
[functions]
  # This tells Netlify to use a modern bundler that will automatically
  # include dependencies like 'axios' from your main package.json.
  node_bundler = "esbuild"

# This rule makes your function available at the user-friendly URL "/api/contact".
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This is the standard rule for Single-Page Apps (like React/Vite).
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200